@startuml PackageDiagram

title Package diagram
!define List java.util.List !define ArrayList java.util.ArrayList

component core {
    package PadelApp.core
    package PadelApp.json
}


component jackson {
}


PadelApp.json ..> jackson

component ui {
    package PadelApp.ui
}
PadelApp.ui ..> PadelApp.core


component javafx {
    component fxml {

    }
}
ui ..> javafx
ui ..> fxml

PadelApp.ui ..> PadelApp.json


@enduml
