@startuml sequenceDiagram

title Sequence Diagram
!define List java.util.List !define ArrayList java.util.ArrayList


user -> AppControllerGames: click: NewRound
AppControllerGames -> Player: addWins
AppControllerGames -> AppControllerGames: shuffel
AppControllerGames -> AppControllerGames: addPlayersToCourts
AppControllerGames -> Player: getWins
AppControllerGames -> AppControllerGames: updateround
user -> AppControllerGames: click: EndGame
AppControllerGames -> Player: addWins
AppControllerGames -> Player: getWins

AppControllerGames -> AppControllerScoreBoard: initialize
AppControllerScoreBoard -> FileManagerJson: getScoreboard
FileManagerJson -> AppControllerScoreBoard: return Scoreboard
AppControllerScoreBoard -> RemoteLeaderboardAccess: sendScoreboard
RemoteLeaderboardAccess -> PadelModelController: send
PadelModelController -> PadelModelService: receiveScoreboard
PadelModelService -> FileManagerJson: saveScoreboard
PadelModelService -> Leaderboard: addScoreboard
AppControllerScoreBoard -> RemoteLeaderboardAccess: getLeaderboard
RemoteLeaderboardAccess -> PadelModelController: send
PadelModelController -> PadelModelService: getLeaderboard
PadelModelService -> FileManagerJson: getLeaderboard
FileManagerJson -> AppControllerScoreBoard: return Leaderboard
AppControllerScoreBoard -> user: populateLeaderboard
AppControllerScoreBoard -> user: populateScoreboard

@enduml